
#line 3 "lex.Conf.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer Conf_create_buffer
#define yy_delete_buffer Conf_delete_buffer
#define yy_flex_debug Conf_flex_debug
#define yy_init_buffer Conf_init_buffer
#define yy_flush_buffer Conf_flush_buffer
#define yy_load_buffer_state Conf_load_buffer_state
#define yy_switch_to_buffer Conf_switch_to_buffer
#define yyin Confin
#define yyleng Confleng
#define yylex Conflex
#define yylineno Conflineno
#define yyout Confout
#define yyrestart Confrestart
#define yytext Conftext
#define yywrap Confwrap
#define yyalloc Confalloc
#define yyrealloc Confrealloc
#define yyfree Conffree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Confrestart(Confin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int Confleng;

extern FILE *Confin, *Confout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Conftext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up Conftext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Confrestart()), so that the user can continue scanning by
	 * just pointing Confin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when Conftext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int Confleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow Confwrap()'s to do buffer switches
 * instead of setting up a fresh Confin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void Confrestart (FILE *input_file  );
void Conf_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE Conf_create_buffer (FILE *file,int size  );
void Conf_delete_buffer (YY_BUFFER_STATE b  );
void Conf_flush_buffer (YY_BUFFER_STATE b  );
void Confpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void Confpop_buffer_state (void );

static void Confensure_buffer_stack (void );
static void Conf_load_buffer_state (void );
static void Conf_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER Conf_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE Conf_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE Conf_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE Conf_scan_bytes (yyconst char *bytes,int len  );

void *Confalloc (yy_size_t  );
void *Confrealloc (void *,yy_size_t  );
void Conffree (void *  );

#define yy_new_buffer Conf_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Confensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Conf_create_buffer(Confin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Confensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Conf_create_buffer(Confin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *Confin = (FILE *) 0, *Confout = (FILE *) 0;

typedef int yy_state_type;

extern int Conflineno;

int Conflineno = 1;

extern char *Conftext;
#define yytext_ptr Conftext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Conftext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	Confleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[474] =
    {   0,
        1,    1,    1,    1,   46,   46,   48,   47,    1,    2,
        6,   47,   43,   41,   42,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,    4,    5,    3,
       44,   46,   45,    1,   41,   43,    0,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   44,   46,   40,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   13,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   33,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   29,   43,
       34,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   12,   43,   43,   30,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   17,   16,
       19,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   35,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   10,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,    9,   43,   43,   18,   43,   39,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   32,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   36,   43,   43,   43,   43,   31,   14,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   26,   43,   43,   37,   43,   43,   43,   43,   43,
       43,   43,   43,   25,   23,   43,   43,   43,   43,   43,
       43,   43,   43,   15,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   27,   43,   43,   43,   43,   43,
        7,   43,   43,   43,   20,   43,   43,   43,   43,    8,
       43,   43,   43,   43,   43,   43,   43,   43,   38,   43,
       11,   43,   22,   43,   43,   28,   21,   43,   43,   43,
       43,   24,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    5,    6,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,    1,    1,
        7,    1,    1,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,    7,   20,   21,   22,   23,   24,
        7,   25,   26,   27,   28,   29,    7,   30,   31,   32,
       33,    1,   34,    1,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,    7,   46,   47,   48,
       49,   50,    7,   51,   52,   53,   54,   55,    7,   56,
       57,   58,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    3,    3,    3,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[477] =
    {   0,
        0,    0,   56,    0,   58,   60,  943,  944,  940,  944,
      944,  933,    0,   65,  944,   44,   61,   42,   53,   58,
      103,   60,   61,   71,  104,   62,   87,  944,  944,  944,
        0,  122,  944,  938,  114,    0,  931,  110,  106,  106,
      118,  120,  122,  105,  120,  121,  116,  113,  115,  122,
      124,  129,  126,  131,    0,  176,  930,  142,  139,  144,
      156,  168,  163,  155,  173,  902,  159,  158,  176,  176,
      164,  173,  165,  179,  165,  181,  169,  173,  186,  175,
      192,  175,  175,  901,  185,  217,  207,  202,  195,  211,
      206,  217,  222,  900,  211,  899,  225,  222,  216,  219,

      222,  218,  229,  225,  898,  232,  232,  230,  227,  232,
      238,  232,  242,  250,  250,  252,  266,  259,  897,  259,
      261,  259,  273,  272,  278,  278,  267,  272,  273,  285,
      281,  291,  281,  896,  895,  894,  295,  292,  284,  281,
      283,  304,  306,  312,  315,  313,  309,  313,  315,  326,
      331,  331,  333,  321,  326,  324,  325,  327,  329,  329,
      330,  335,  335,  332,  339,  338,  348,  893,  354,  368,
      369,  892,  378,  369,  380,  371,  370,  379,    0,  379,
      385,  386,  387,  388,  372,  891,  377,  380,    0,  383,
        0,  380,  890,  388,  395,  392,  386,  889,  392,  888,

      887,  401,  886,  400,  401,  403,  412,  420,  415,  418,
      419,  420,  431,  425,  423,  426,  423,  438,  426,  885,
      438,  431,  433,  443,  452,  446,  447,  439,  450,  457,
      464,  461,  482,  473,  471,  485,  469,  477,  481,  476,
      485,  476,  477,  490,  482,  489,  487,  490,    0,    0,
        0,  486,  485,  492,  497,  491,  503,  516,  507,  884,
      524,  513,  524,  520,  523,  524,  528,  525,  521,  538,
      532,  883,  528,  538,  534,  547,  547,  547,  552,  541,
      543,  556,  539,  545,  547,  570,  570,  563,  571,  578,
      583,  574,  587,  882,  584,  580,  575,  583,  583,  590,

      593,  583,  582,  589,  586,  604,  604,  597,  586,  590,
      600,  607,  619,  624,  881,  612,  618,    0,  622,  880,
      879,  639,  632,  624,  877,  641,  626,  631,  645,  638,
      866,  632,    0,  633,  648,    0,  636,    0,  645,  645,
      645,  645,  863,  643,  652,  648,  656,  646,  672,  674,
      861,  672,  668,    0,  678,  678,  676,  681,  678,  687,
      686,  682,  677,  691,  682,  682,  697,  688,  699,  705,
      710,    0,  858,  703,  690,  705,    0,  700,  702,  727,
      726,  728,  731,  725,  735,  741,  729,  724,  743,  731,
      749,  738,  741,  750,  742,  740,  753,  740,  756,  754,

      759,    0,  743,  750,  752,  751,  761,  778,  776,  772,
      786,  780,  774,    0,    0,  797,  798,   64,  782,  785,
      788,  794,  800,  790,  802,  796,  794,  794,  804,  814,
      803,  803,  799,  818,    0,  803,  831,  821,  823,  822,
        0,  834,  847,  833,    0,  838,   60,  838,  843,    0,
      842,  853,  838,  844,  840,  845,  843,  850,    0,  855,
        0,  852,    0,  850,  861,    0,    0,  853,  869,  853,
      867,    0,  944,  907,   84,  910
    } ;

static yyconst flex_int16_t yy_def[477] =
    {   0,
      473,    1,    1,    3,  474,  474,  473,  473,  473,  473,
      473,  473,  475,  473,  473,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  473,  473,  473,
      476,  473,  473,  473,  473,  475,  473,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  476,  473,  473,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,

      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,

      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,

      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,

      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,    0,  473,  473,  473
    } ;

static yyconst flex_int16_t yy_nxt[1003] =
    {   0,
        8,    9,   10,   11,   12,   13,   13,   14,   15,   16,
       13,   17,   13,   18,   13,   13,   13,   19,   13,   20,
       21,   22,   23,   24,   13,   25,   26,   13,   27,   13,
       13,   13,   28,   29,   13,   16,   13,   17,   13,   18,
       13,   13,   13,   19,   13,   20,   21,   22,   23,   24,
       13,   25,   26,   13,   27,   13,   13,   13,   30,   32,
       32,   32,   32,   38,    8,   13,   33,   13,   33,   13,
       37,   41,   35,   13,   42,   13,   13,   13,   13,   13,
       43,   13,   13,   39,   13,   40,   36,   47,   48,   38,
       49,   13,   53,   13,  454,   13,   54,   41,  428,   13,

       42,   13,   13,   13,   13,   13,   43,   13,   13,   39,
       13,   40,   44,   47,   48,   50,   49,   51,   53,   37,
       45,   35,   54,   56,   56,   58,   52,   59,   60,   61,
       46,   62,   63,   65,   66,   67,   70,   64,   44,   71,
       68,   50,   72,   51,   73,   74,   45,   69,   75,   76,
       77,   58,   52,   59,   60,   61,   46,   62,   63,   65,
       66,   67,   70,   64,   78,   71,   68,   79,   72,   80,
       73,   74,   81,   69,   75,   76,   77,   56,   56,   82,
       83,   84,   85,   87,   88,   89,   90,   91,   92,   93,
       78,   94,   95,   79,   96,   80,   97,   98,   81,   99,

      100,  101,  102,  103,  105,   82,   83,   84,   85,   87,
       88,   89,   90,   91,   92,   93,  109,   94,   95,  110,
       96,  111,   97,   98,  112,   99,  100,  101,  102,  103,
      105,  106,  107,  113,  114,  115,  108,  117,  119,  120,
      121,  122,  109,  123,  124,  110,  125,  111,  126,  128,
      112,  129,  130,  131,  132,  133,  134,  106,  107,  113,
      114,  115,  108,  117,  119,  120,  121,  122,  135,  123,
      124,  136,  125,  137,  126,  128,  138,  129,  130,  131,
      132,  133,  134,  139,  140,  142,  143,  144,  145,  146,
      147,  148,  150,  151,  135,  152,  153,  136,  154,  137,

      149,  155,  138,  156,  160,  161,  162,  163,  164,  139,
      140,  142,  143,  144,  145,  146,  147,  148,  150,  151,
      165,  152,  153,  166,  154,  167,  149,  155,  168,  156,
      160,  161,  162,  163,  164,  169,  170,  171,  172,  173,
      174,  175,  176,  177,  178,  179,  165,  180,  181,  166,
      182,  167,  183,  184,  168,  185,  186,  187,  188,  189,
      190,  169,  170,  171,  172,  173,  174,  175,  176,  177,
      178,  179,  191,  180,  181,  193,  182,  194,  183,  184,
      195,  185,  186,  187,  188,  189,  190,  197,  198,  199,
      200,  201,  202,  203,  204,  205,  206,  207,  191,  208,

      210,  193,  211,  194,  212,  213,  195,  215,  216,  217,
      218,  220,  223,  197,  198,  199,  200,  201,  202,  203,
      204,  205,  206,  207,  225,  208,  210,  226,  211,  227,
      212,  213,  228,  215,  216,  217,  218,  220,  223,  229,
      230,  231,  232,  233,  234,  235,  236,  237,  238,  239,
      225,  240,  242,  226,  243,  227,  244,  245,  228,  246,
      247,  248,  249,  250,  251,  229,  230,  231,  232,  233,
      234,  235,  236,  237,  238,  239,  252,  240,  242,  253,
      243,  254,  244,  245,  255,  246,  247,  248,  249,  250,
      251,  256,  257,  258,  259,  260,  261,  262,  263,  264,

      265,  266,  252,  267,  268,  253,  269,  254,  270,  271,
      255,  272,  273,  274,  275,  276,  277,  256,  257,  258,
      259,  260,  261,  262,  263,  264,  265,  266,  278,  267,
      268,  279,  269,  281,  270,  271,  282,  272,  273,  274,
      275,  276,  277,  283,  284,  285,  286,  287,  288,  289,
      290,  291,  293,  294,  278,  295,  296,  279,  297,  281,
      298,  299,  282,  300,  301,  302,  303,  304,  305,  283,
      284,  285,  286,  287,  288,  289,  290,  291,  293,  294,
      306,  295,  296,  307,  297,  308,  298,  299,  309,  300,
      301,  302,  303,  304,  305,  310,  311,  312,  313,  315,

      316,  317,  318,  319,  320,  321,  306,  322,  323,  307,
      324,  308,  325,  326,  309,  327,  328,  329,  330,  331,
      332,  310,  311,  312,  313,  315,  316,  317,  318,  319,
      320,  321,  333,  322,  323,  334,  324,  336,  325,  326,
      337,  327,  328,  329,  330,  331,  332,  338,  341,  342,
      343,  345,  346,  347,  348,  349,  351,  352,  333,  353,
      354,  334,  355,  336,  356,  357,  337,  358,  360,  361,
      362,  363,  364,  338,  341,  342,  343,  345,  346,  347,
      348,  349,  351,  352,  365,  353,  354,  366,  355,  368,
      356,  357,  369,  358,  360,  361,  362,  363,  364,  370,

      371,  372,  373,  374,  375,  376,  377,  378,  379,  380,
      365,  381,  382,  366,  383,  368,  384,  385,  369,  386,
      388,  389,  390,  391,  392,  370,  371,  372,  373,  374,
      375,  376,  377,  378,  379,  380,  393,  381,  382,  394,
      383,  395,  384,  385,  396,  386,  388,  389,  390,  391,
      392,  397,  398,  399,  400,  401,  402,  403,  404,  405,
      406,  407,  393,  408,  409,  394,  410,  395,  411,  412,
      396,  413,  414,  415,  416,  417,  418,  397,  398,  399,
      400,  401,  402,  403,  404,  405,  406,  407,  419,  408,
      409,  420,  410,  421,  411,  412,  422,  413,  414,  415,

      416,  417,  418,  423,  424,  425,  426,  427,  429,  430,
      431,  432,  433,  434,  419,  435,  436,  420,  437,  421,
      438,  439,  422,  440,  441,  442,  443,  444,  445,  423,
      424,  425,  426,  427,  429,  430,  431,  432,  433,  434,
      446,  435,  436,  447,  437,  448,  438,  439,  449,  440,
      441,  442,  443,  444,  445,  450,  451,  452,  453,  455,
      456,  457,  458,  459,  460,  461,  446,  462,  463,  447,
      464,  448,  465,  466,  449,  467,  468,  469,  470,  471,
      472,  450,  451,  452,  453,  455,  456,  457,  458,  459,
      460,  461,  387,  462,  463,  367,  464,  359,  465,  466,

      350,  467,  468,  469,  470,  471,  472,   31,   31,   31,
       55,  344,   55,  340,  339,  335,  314,  292,  280,  241,
      224,  222,  221,  219,  214,  209,  196,  192,  159,  158,
      157,  141,  127,  118,  116,  104,   86,   57,   57,   34,
       35,   34,  473,    7,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,

      473,  473
    } ;

static yyconst flex_int16_t yy_chk[1003] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    5,
        5,    6,    6,   16,    3,    3,    5,    3,    6,    3,
       14,   18,   14,    3,   19,    3,    3,    3,    3,    3,
       20,    3,    3,   17,    3,   17,  475,   22,   23,   16,
       24,    3,   26,    3,  447,    3,   27,   18,  418,    3,

       19,    3,    3,    3,    3,    3,   20,    3,    3,   17,
        3,   17,   21,   22,   23,   25,   24,   25,   26,   35,
       21,   35,   27,   32,   32,   38,   25,   39,   40,   41,
       21,   41,   42,   43,   44,   45,   47,   42,   21,   48,
       46,   25,   49,   25,   50,   51,   21,   46,   52,   53,
       54,   38,   25,   39,   40,   41,   21,   41,   42,   43,
       44,   45,   47,   42,   58,   48,   46,   59,   49,   60,
       50,   51,   61,   46,   52,   53,   54,   56,   56,   62,
       63,   64,   65,   67,   68,   69,   70,   71,   72,   73,
       58,   74,   75,   59,   76,   60,   77,   78,   61,   79,

       80,   81,   82,   83,   85,   62,   63,   64,   65,   67,
       68,   69,   70,   71,   72,   73,   87,   74,   75,   88,
       76,   89,   77,   78,   90,   79,   80,   81,   82,   83,
       85,   86,   86,   91,   92,   93,   86,   95,   97,   98,
       99,  100,   87,  101,  102,   88,  103,   89,  104,  106,
       90,  107,  108,  109,  110,  111,  112,   86,   86,   91,
       92,   93,   86,   95,   97,   98,   99,  100,  113,  101,
      102,  114,  103,  115,  104,  106,  116,  107,  108,  109,
      110,  111,  112,  117,  118,  120,  121,  122,  123,  124,
      125,  126,  127,  128,  113,  129,  130,  114,  131,  115,

      126,  132,  116,  133,  137,  138,  139,  140,  141,  117,
      118,  120,  121,  122,  123,  124,  125,  126,  127,  128,
      142,  129,  130,  143,  131,  144,  126,  132,  145,  133,
      137,  138,  139,  140,  141,  146,  147,  148,  149,  150,
      151,  152,  153,  154,  155,  156,  142,  157,  157,  143,
      158,  144,  159,  160,  145,  161,  162,  163,  164,  165,
      166,  146,  147,  148,  149,  150,  151,  152,  153,  154,
      155,  156,  167,  157,  157,  169,  158,  170,  159,  160,
      171,  161,  162,  163,  164,  165,  166,  173,  174,  175,
      176,  177,  178,  180,  181,  182,  183,  184,  167,  185,

      187,  169,  188,  170,  190,  192,  171,  194,  195,  196,
      197,  199,  202,  173,  174,  175,  176,  177,  178,  180,
      181,  182,  183,  184,  204,  185,  187,  205,  188,  206,
      190,  192,  207,  194,  195,  196,  197,  199,  202,  208,
      209,  210,  211,  212,  213,  214,  215,  216,  217,  218,
      204,  219,  221,  205,  222,  206,  222,  222,  207,  223,
      224,  225,  226,  227,  228,  208,  209,  210,  211,  212,
      213,  214,  215,  216,  217,  218,  229,  219,  221,  230,
      222,  231,  222,  222,  232,  223,  224,  225,  226,  227,
      228,  233,  234,  235,  236,  237,  238,  239,  240,  241,

      242,  243,  229,  244,  245,  230,  246,  231,  247,  248,
      232,  252,  253,  254,  255,  256,  257,  233,  234,  235,
      236,  237,  238,  239,  240,  241,  242,  243,  258,  244,
      245,  259,  246,  261,  247,  248,  262,  252,  253,  254,
      255,  256,  257,  263,  264,  265,  266,  267,  268,  269,
      270,  271,  273,  274,  258,  275,  276,  259,  277,  261,
      278,  279,  262,  280,  281,  282,  283,  284,  285,  263,
      264,  265,  266,  267,  268,  269,  270,  271,  273,  274,
      286,  275,  276,  287,  277,  288,  278,  279,  289,  280,
      281,  282,  283,  284,  285,  290,  291,  292,  293,  295,

      296,  297,  298,  299,  300,  301,  286,  302,  303,  287,
      304,  288,  305,  306,  289,  307,  308,  309,  310,  311,
      312,  290,  291,  292,  293,  295,  296,  297,  298,  299,
      300,  301,  313,  302,  303,  314,  304,  316,  305,  306,
      317,  307,  308,  309,  310,  311,  312,  319,  322,  323,
      324,  326,  327,  328,  329,  330,  332,  334,  313,  335,
      337,  314,  339,  316,  340,  341,  317,  342,  344,  345,
      346,  347,  348,  319,  322,  323,  324,  326,  327,  328,
      329,  330,  332,  334,  349,  335,  337,  350,  339,  352,
      340,  341,  353,  342,  344,  345,  346,  347,  348,  355,

      356,  357,  358,  359,  360,  361,  362,  363,  364,  365,
      349,  366,  367,  350,  368,  352,  369,  370,  353,  371,
      374,  375,  376,  378,  379,  355,  356,  357,  358,  359,
      360,  361,  362,  363,  364,  365,  380,  366,  367,  381,
      368,  382,  369,  370,  383,  371,  374,  375,  376,  378,
      379,  384,  385,  386,  387,  388,  389,  390,  391,  392,
      393,  394,  380,  395,  396,  381,  397,  382,  398,  399,
      383,  400,  401,  403,  404,  405,  406,  384,  385,  386,
      387,  388,  389,  390,  391,  392,  393,  394,  407,  395,
      396,  408,  397,  409,  398,  399,  410,  400,  401,  403,

      404,  405,  406,  411,  412,  413,  416,  417,  419,  420,
      421,  422,  423,  424,  407,  425,  426,  408,  427,  409,
      428,  429,  410,  430,  431,  432,  433,  434,  436,  411,
      412,  413,  416,  417,  419,  420,  421,  422,  423,  424,
      437,  425,  426,  438,  427,  439,  428,  429,  440,  430,
      431,  432,  433,  434,  436,  442,  443,  444,  446,  448,
      449,  451,  452,  453,  454,  455,  437,  456,  457,  438,
      458,  439,  460,  462,  440,  464,  465,  468,  469,  470,
      471,  442,  443,  444,  446,  448,  449,  451,  452,  453,
      454,  455,  373,  456,  457,  351,  458,  343,  460,  462,

      331,  464,  465,  468,  469,  470,  471,  474,  474,  474,
      476,  325,  476,  321,  320,  315,  294,  272,  260,  220,
      203,  201,  200,  198,  193,  186,  172,  168,  136,  135,
      134,  119,  105,   96,   94,   84,   66,   57,   37,   34,
       12,    9,    7,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,

      473,  473
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int Conf_flex_debug;
int Conf_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Conftext;
#line 1 "../parseConf.l"
/***********************************************************************************
 * AUTORES
 *   - Ofelia González Pérez
 *   - Gara Miranda Valladares
 *   - Carlos Segura González
 *   - Eduardo Manuel Segredo González
 * 
 * FECHA
 *    Noviembre 2007
 * 
 * DESCRIPCION
 *    Analizador léxico del fichero de configuración para las ejecuciones
 *    paralelas
 *
 ***********************************************************************************/
#line 19 "../parseConf.l"
#include <string.h>
#include <string>
#include <iostream>

using namespace std;

#include "Configuration.h"
#include "parseConf.tab.h"

double realValueConf;
string stringValueConf;

 

#line 885 "lex.Conf.c"

#define INITIAL 0
#define DEV_NEWLINES 1
#define LINEA_COMPLETA 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Conflex_destroy (void );

int Confget_debug (void );

void Confset_debug (int debug_flag  );

YY_EXTRA_TYPE Confget_extra (void );

void Confset_extra (YY_EXTRA_TYPE user_defined  );

FILE *Confget_in (void );

void Confset_in  (FILE * in_str  );

FILE *Confget_out (void );

void Confset_out  (FILE * out_str  );

int Confget_leng (void );

char *Confget_text (void );

int Confget_lineno (void );

void Confset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Confwrap (void );
#else
extern int Confwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( Conftext, Confleng, 1, Confout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( Confin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( Confin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, Confin))==0 && ferror(Confin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(Confin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Conflex (void);

#define YY_DECL int Conflex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after Conftext and Confleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 35 "../parseConf.l"


#line 1077 "lex.Conf.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! Confin )
			Confin = stdin;

		if ( ! Confout )
			Confout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Confensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				Conf_create_buffer(Confin,YY_BUF_SIZE );
		}

		Conf_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of Conftext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 474 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 944 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "../parseConf.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 38 "../parseConf.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 39 "../parseConf.l"
{ BEGIN 0; return NEWLINE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "../parseConf.l"
{ return CORCHETE_ABIERTO; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "../parseConf.l"
{ BEGIN 0; return CORCHETE_CERRADO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "../parseConf.l"
{ return COMA; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "../parseConf.l"
{ return TYPE_STOPPING_CRITERION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "../parseConf.l"
{ return VALUE_STOPPING_CRITERION; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "../parseConf.l"
{ return SOLUTION_SOURCE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "../parseConf.l"
{ return EXECUTION_MODEL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "../parseConf.l"
{ return NUMBER_PARALLEL_EXECUTIONS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "../parseConf.l"
{ return CONVERSION; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "../parseConf.l"
{ return SCORE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "../parseConf.l"
{ return MIGRATION_TOPOLOGY; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "../parseConf.l"
{ return INIT_POP_ISLAND_LOADER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "../parseConf.l"
{ return PLUGIN_PATH; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "../parseConf.l"
{ return OUTPUT_PATH; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "../parseConf.l"
{ BEGIN LINEA_COMPLETA; return CONVERSIONPARAMS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "../parseConf.l"
{ BEGIN LINEA_COMPLETA; return SCOREPARAMS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "../parseConf.l"
{ BEGIN LINEA_COMPLETA; return MIGRATION_TOPOLOGY_PARAMS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "../parseConf.l"
{ BEGIN LINEA_COMPLETA; return INIT_POP_ISLAND_LOADER_PARAMS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "../parseConf.l"
{ return INIT_PERCENT_OF_INDIVIDUALS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "../parseConf.l"
{ return MIGRATION_PROBABILITY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "../parseConf.l"
{ return NUMBER_OF_INDIVIDUALS_TO_MIGRATE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "../parseConf.l"
{ return MAX_GLOBAL_FRONT_SIZE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "../parseConf.l"
{ return MAX_LOCAL_FRONT_SIZE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "../parseConf.l"
{ return MAX_FINAL_SOLUTION_SIZE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "../parseConf.l"
{ return SEND_RESULTS_PER_GENERATION; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "../parseConf.l"
{ return ALGORITHM; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "../parseConf.l"
{ return INDIVIDUAL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "../parseConf.l"
{ return MIGRATION_SELECTOR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "../parseConf.l"
{ return EXCHANGE_SELECTOR; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "../parseConf.l"
{ return MUTATION; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "../parseConf.l"
{ return CROSSOVER; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "../parseConf.l"
{ return LOCAL_SEARCH; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "../parseConf.l"
{ BEGIN LINEA_COMPLETA; return LOCAL_SEARCH_PARAMS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "../parseConf.l"
{ return MULTIOBJECTIVIZATION; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "../parseConf.l"
{ BEGIN LINEA_COMPLETA; return MULTIOBJECTIVIZATION_PARAMS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "../parseConf.l"
{ BEGIN LINEA_COMPLETA; return INDIVIDUALPARAMS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "../parseConf.l"
{ BEGIN DEV_NEWLINES; realValueConf = atof(Conftext); return NUMERO; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "../parseConf.l"
{ BEGIN DEV_NEWLINES; realValueConf = (double) atoi(Conftext); return NUMERO; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "../parseConf.l"
{ return DOS_PUNTOS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "../parseConf.l"
{ BEGIN DEV_NEWLINES; stringValueConf = Conftext; return STRING; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "../parseConf.l"
{ BEGIN 0; stringValueConf = Conftext; return STRING; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "../parseConf.l"
{ return DOS_PUNTOS;}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 82 "../parseConf.l"
{}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 84 "../parseConf.l"
ECHO;
	YY_BREAK
#line 1398 "lex.Conf.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DEV_NEWLINES):
case YY_STATE_EOF(LINEA_COMPLETA):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed Confin at a new source and called
			 * Conflex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = Confin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( Confwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * Conftext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of Conflex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Confrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Confrestart(Confin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) Confrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 474 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 474 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 473);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up Conftext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Confrestart(Confin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Confwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve Conftext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Confrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        Confensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            Conf_create_buffer(Confin,YY_BUF_SIZE );
	}

	Conf_init_buffer(YY_CURRENT_BUFFER,input_file );
	Conf_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void Conf_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Confpop_buffer_state();
	 *		Confpush_buffer_state(new_buffer);
     */
	Confensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Conf_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (Confwrap()) processing, but the only time this flag
	 * is looked at is after Confwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void Conf_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	Confin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Conf_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Confalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Conf_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) Confalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Conf_create_buffer()" );

	b->yy_is_our_buffer = 1;

	Conf_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Conf_create_buffer()
 * 
 */
    void Conf_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		Conffree((void *) b->yy_ch_buf  );

	Conffree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Confrestart() or at EOF.
 */
    static void Conf_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	Conf_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then Conf_init_buffer was _probably_
     * called from Confrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void Conf_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Conf_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void Confpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	Confensure_buffer_stack();

	/* This block is copied from Conf_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Conf_switch_to_buffer. */
	Conf_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void Confpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	Conf_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		Conf_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Confensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)Confalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Confensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)Confrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Confensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE Conf_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) Confalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Conf_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	Conf_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Conflex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Conf_scan_bytes() instead.
 */
YY_BUFFER_STATE Conf_scan_string (yyconst char * yystr )
{
    
	return Conf_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to Conflex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Conf_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) Confalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Conf_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Conf_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Conf_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Conftext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		Conftext[Confleng] = (yy_hold_char); \
		(yy_c_buf_p) = Conftext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		Confleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int Confget_lineno  (void)
{
        
    return Conflineno;
}

/** Get the input stream.
 * 
 */
FILE *Confget_in  (void)
{
        return Confin;
}

/** Get the output stream.
 * 
 */
FILE *Confget_out  (void)
{
        return Confout;
}

/** Get the length of the current token.
 * 
 */
int Confget_leng  (void)
{
        return Confleng;
}

/** Get the current token.
 * 
 */

char *Confget_text  (void)
{
        return Conftext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void Confset_lineno (int  line_number )
{
    
    Conflineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see Conf_switch_to_buffer
 */
void Confset_in (FILE *  in_str )
{
        Confin = in_str ;
}

void Confset_out (FILE *  out_str )
{
        Confout = out_str ;
}

int Confget_debug  (void)
{
        return Conf_flex_debug;
}

void Confset_debug (int  bdebug )
{
        Conf_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Conflex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    Confin = stdin;
    Confout = stdout;
#else
    Confin = (FILE *) 0;
    Confout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Conflex_init()
     */
    return 0;
}

/* Conflex_destroy is for both reentrant and non-reentrant scanners. */
int Conflex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Conf_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Confpop_buffer_state();
	}

	/* Destroy the stack itself. */
	Conffree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Conflex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Confalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *Confrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void Conffree (void * ptr )
{
	free( (char *) ptr );	/* see Confrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 84 "../parseConf.l"



int Confwrap(){ return 1; }

